version: '3.8'
services:
  exchange-service:
    build:
      .
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/accounts

  database:
    image: postgres:14.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounts