server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: exchange-service
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5433/accounts
    username: postgres
    password: postgres
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    schemas: configurations
    baseline-on-migrate: true

exchange:
  provider:
    rest:
      host: http://api.nbp.pl/api
      averageExchangeRatesEndpoint: /exchangerates/rates/a/{currency}/