spring:
  application:
    name: exchange-service-integration-test
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    schemas: accounts
    baseline-on-migrate: true